# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 09:49
from __future__ import unicode_literals

import UnixTimestampField
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serverList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=100, unique=True)),
                ('hostcomputer', models.CharField(max_length=255)),
                ('cpucore', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('system', models.CharField(max_length=255)),
                ('systemdisk', models.IntegerField()),
                ('datadisk', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(max_length=100)),
                ('use', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('alter_time', UnixTimestampField.UnixTimestampField(null=True)),
            ],
        ),
    ]
