# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_serverlist_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='alter_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 7, 27, 17, 46, 58, 137380)),
            preserve_default=False,
        ),
    ]
