# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0003_auto_20170727_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverlist',
            options={'ordering': ['id']},
        ),
    ]
