# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0004_auto_20170810_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='cpucore',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='datadisk',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='memory',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='systemdisk',
            field=models.CharField(max_length=255),
        ),
    ]
