# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0005_auto_20170811_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='datadisk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
